### ISSUE TITLE
Default constructor is missing

### ISSUE THREAD

**Issue by ahdach** [gr0mazeka/StephenPrata#1]
Hi,
Thanks for this repo. Very helpful.
Just noticed last night that the default constructor for Golf was missing here:
[https://github.com/gr0mazeka/StephenPrata/blob/master/chapter_10/sol_10_03/golf_10.h](url)

Regards,
M

**Comment by gr0mazeka** [comment]
Golf(const char *name = "", int hc = 0); // default constructor

**Comment by ahdach** [comment]
Hi,

On my xCode project, I had to add
Golf();
on top of the alternative constructor. Otherwise, the declaration:
Golf arr[SIZE];
would raise an error:
No matching constructor for initialization of 'Golf [5]' .

I read that C++ would provide the constructor Golf() unless you define another one.

Maybe it is platform dependant.

Thanks for your prompt response.
M

**Comment by gr0mazeka** [comment]
No problems. Believe in yourself and good things will happen to you!
